{
 "title": "Geodata Examples",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Maps of Germany", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Population density germany",
   "type": "geomap",
   "description": "source:\nhttps://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugQ/AuszugGV3QAktuell.html",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "general",
     "rawSql": "SELECT\n-- *,\nname,\ninsgesamt AS population,\n-- gemeinde,\nCAST(REPLACE(`längengrad`, ',', '.') AS float) as longitude,\nCAST(REPLACE(breitengrad, ',', '.') AS double) as latitude\nFROM general.`words-cities-germany`\nWHERE gemeinde <> \"\"\nORDER BY insgesamt DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Shapes of communities in NRW",
   "type": "orchestracities-map-panel",
   "description": "This visualization uses the plugin \"Orchestra Cities Map\". It loads the data as geojson from a db.\nThe original data comes from basemap.de",
   "gridPos": { "h": 17, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "dataset": "general",
     "rawSql": "SELECT geojson, name, population\nFROM general.`words-cities-germany-shapes`\nWHERE AGS like '05%'"
    },
    {
     "dataset": "general",
     "rawSql": "SELECT geojson, name, population\nFROM general.`words-cities-germany-shapes`\nWHERE AGS like '05%' AND name LIKE '%dorf'"
    }
   ]
  },
  { "title": "Tabular data from germany", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "List of all cities in germany",
   "type": "table",
   "description": "souce: source:\nhttps://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugQ/AuszugGV3QAktuell.html",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "general",
     "rawSql": "SELECT\n-- *,\nname AS Name,\nplz,\ninsgesamt AS population,\nmännlich AS population_male,\nweiblich AS population_female\nFROM general.`words-cities-germany`\nWHERE gemeinde <> \"\" AND `insgesamt` > 0\nORDER BY insgesamt DESC"
    }
   ]
  },
  {
   "title": "Largest german cIties",
   "type": "bargauge",
   "description": "Germanys largest cities",
   "gridPos": { "h": 17, "w": 6, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "dataset": "general",
     "rawSql": "SELECT\nname, insgesamt\n-- name,\n-- insgesamt AS population,\n-- gemeinde,\n-- CAST(REPLACE(`längengrad`, ',', '.') AS float) as longitude,\n-- CAST(REPLACE(breitengrad, ',', '.') AS double) as latitude\nFROM general.`words-cities-germany`\nWHERE gemeinde <> \"\"\nORDER BY insgesamt DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Smallest german cIties",
   "type": "bargauge",
   "description": "Germanys largest cities",
   "gridPos": { "h": 17, "w": 6, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "dataset": "general",
     "rawSql": "SELECT\nname, insgesamt\n-- name,\n-- insgesamt AS population,\n-- gemeinde,\n-- CAST(REPLACE(`längengrad`, ',', '.') AS float) as longitude,\n-- CAST(REPLACE(breitengrad, ',', '.') AS double) as latitude\nFROM general.`words-cities-germany`\nWHERE gemeinde <> \"\" AND insgesamt > 0\nORDER BY insgesamt ASC\nLIMIT 15"
    }
   ]
  },
  { "title": "Data direct from geojson-files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Borders of german communities",
   "type": "geomap",
   "description": "The border of all communities in germany.\nsource: https://opendatalab.de/projects/geojson-utilities/\nThe data comes from a local geojson-file",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "general",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Community borders Northrine-Westphalia",
   "type": "geomap",
   "description": "The data comes from a local geojson-file",
   "gridPos": { "h": 16, "w": 10, "x": 7, "y": 37 },
   "targets": [
    { "dataset": "general" }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Global Cities - coastline",
   "type": "geomap",
   "description": "source:\nglobal-cities",
   "gridPos": { "h": 18, "w": 14, "x": 0, "y": 55 },
   "targets": [
    {
     "dataset": "general",
     "rawSql": "SELECT\nname,\npopulation,\ndigital_elevation_model,\nlongitude,\nlatitude\nFROM general.`words-cities-global`\nWHERE digital_elevation_model < 5 -- population > 100000"
    }
   ]
  }
 ]
}