{
 "title": "Millverse",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Incident Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How many repairs per time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', incident_fix) AS time,\n  COUNT(*) AS resolved_count\nFROM\n  incidents\nWHERE\n  incident_fix IS NOT NULL\n  AND $__timeFilter(incident_fix)\nGROUP BY\n  time\nORDER BY\n  time;\n"
    }
   ]
  },
  {
   "title": "Incidents count",
   "type": "timeseries",
   "description": "How many new incidents appear",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', incident_start) AS time,\n  COUNT(*) AS incident_count\nFROM\n  incidents\nGROUP BY\n  time\nORDER BY\n  time ASC;"
    }
   ]
  },
  {
   "title": "Time to repair Average",
   "type": "gauge",
   "description": "The average over all incidents from when does the incident happened to when it has been fixed",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(time_to_repair) /1000 AS avg_time_to_repair\nFROM\n  incidents\nWHERE\n  $__timeFilter(incident_fix)"
    }
   ]
  },
  {
   "title": "Unsolved",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS open_incidents\nFROM\n  incidents\nWHERE\n  incident_fix IS NULL\n"
    }
   ]
  },
  {
   "title": "Solved",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS solved_incidents\nFROM\n  incidents\nWHERE\n  incident_fix IS NOT NULL;"
    }
   ]
  },
  {
   "title": "All Incidents",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS open_incidents\nFROM\n  incidents"
    }
   ]
  },
  {
   "title": "Table overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select * from incidents order by incident_start"
    }
   ]
  },
  { "title": "Database Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Database connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_activity WHERE datname = 'general';"
    }
   ]
  }
 ]
}