# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: mariaDbProvisioning
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: mariaDbProvisioning
  # <string, required> datasource type. Required
  type: mysql
  # <string, required> access mode. direct or proxy. Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: $__env{PROJECT_NAME}-mariadb:3306
  # <string> database password, if used
  password: $__env{MYSQL_PASSWORD}
  # <string> database user, if used
  #user: "admin"
  user: $__env{MYSQL_USER}
  # <string> database name, if used
  database: $__env{MYSQL_DATABASE}
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault:
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
    password: $__env{MYSQL_PASSWORD}
    #basicAuthPassword: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
