{
 "title": "Millverse",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Incident Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "How many repairs per time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', incident_fix) AS time,\n  COUNT(*) AS \"per minute\"\nFROM\n  incidents\nWHERE\n  incident_fix IS NOT NULL\n  AND $__timeFilter(incident_fix)\nGROUP BY\n  time\nORDER BY\n  time;\n"
    },
    {
     "rawSql": "SELECT\n  date_trunc('second', incident_fix) AS time,\n  COUNT(*) AS \"per second\"\nFROM\n  incidents\nWHERE\n  incident_fix IS NOT NULL\n  AND $__timeFilter(incident_fix)\nGROUP BY\n  time\nORDER BY\n  time;\n"
    }
   ]
  },
  {
   "title": "Incidents count",
   "type": "timeseries",
   "description": "How many new incidents appear",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', incident_start) AS time,\n  COUNT(*) AS incident_count\nFROM\n  incidents\nGROUP BY\n  time\nORDER BY\n  time ASC;"
    },
    {
     "rawSql": "SELECT\n  date_trunc('seconds', incident_start) AS time,\n  COUNT(*) AS incident_count\nFROM\n  incidents\nGROUP BY\n  time\nORDER BY\n  time ASC;"
    }
   ]
  },
  {
   "title": "Repair time (All time)",
   "type": "stat",
   "description": "Alltime Min, Avg. and Max repair time. \n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(time_to_repair)/1000 as \"Minimum\" from incidents"
    },
    {
     "rawSql": "SELECT\n  AVG(time_to_repair) /1000 AS \"Avgerage\"\nFROM\n  incidents"
    },
    {
     "rawSql": "select max(time_to_repair)/1000 as \"Maximum\" from incidents"
    }
   ]
  },
  {
   "title": "Incidents count",
   "type": "stat",
   "description": "The nuber of the open, the fixed, and the sum of all incidents",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"open\" FROM incidents WHERE incident_fix IS NULL\n"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"fixed\" FROM incidents WHERE incident_fix IS NOT NULL;"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"all\" FROM incidents"
    }
   ]
  },
  {
   "title": "Incidents count",
   "type": "piechart",
   "description": "The nuber of the open, the fixed, and the sum of all incidents",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"open\" FROM incidents WHERE incident_fix IS NULL\n"
    },
    {
     "rawSql": "SELECT COUNT(*) AS \"fixed\" FROM incidents WHERE incident_fix IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Repair time (Selected Interval)",
   "type": "stat",
   "description": "The average repair time over the selected time-interval. How long did it took to fix those beeing repaired within the selected time range",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min(time_to_repair)/1000 as \"Minimum\" from incidents\nWHERE $__timeFilter(incident_fix)"
    },
    {
     "rawSql": "SELECT\n  AVG(time_to_repair) /1000 AS \"Average\"\nFROM\n  incidents\nWHERE\n  $__timeFilter(incident_fix)"
    },
    {
     "rawSql": "select max(time_to_repair)/1000 as \"Maximum\" from incidents\nWHERE $__timeFilter(incident_fix)"
    }
   ]
  },
  {
   "title": "Incident table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "select * from incidents order by incident_start"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database connections",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pg_stat_activity WHERE datname = 'general';"
      }
     ]
    }
   ]
  }
 ]
}